pub enum Token {
    // Keywords
    Select,
    From,
    Where,
    OrderBy,
    // Operators
    Add,
    Subtract,
    Multiply,
    Divide,
    EqualTo,
    NotEqualTo,
    GreaterThan,
    LessThan,
    GreaterThanOrEqualTo,
    LessThanOrEqualTo,
    And,
    Or,
    Not,
    Like,
    In,
    // Separators
    Comma,
    Dot,
    LParen,
    RParen,
    Semicolon,
    SingleQuote,
    DoubleQuote,
    LeftBracket,
    RightBracket,
    Backquote,
    Backslash,
    // Literals
    Identifier(String),
    StringLiteral(String),
    IntLiteral(i32),
    FloatLiteral(f32),
    BoolLiteral(bool),
    NullLiteral,
    // Special Characters
    Eof,
    Invalid,
}